### ISSUE TITLE
Error in queries with arrays

### ISSUE THREAD

**Issue by analuisamartins** [electricimp/Parse#1]
Hi,

I'm testing this lib, but in queries with arrays, I'm getting this error and I don't understand why:
"Could not perform query: $in requires an array"        

Is something I'm doing wrong? Thanks in advance.

Code in agent (from the example):

```
    local query = parse.createQuery("sensors")
    query.containedIn("type", ["light", "motion", "thermal", "pressure"])

    query.find(function (err, data) {
        if (err != null)
        {
            server.log ("Could not perform query: " + err.error)
        }
        else
        {
            server.log("The following rooms contain motion or thermal sensors:")

            foreach (sensor in data.results)
            {
              server.log("Room " + sensor.room)
            }
        }
    }) 
```

**Comment by cat-haines** [comment]
Verified! Looks like this is a bug in our library.

It's been a while since I've looked at this code/Parse, but shouldn't be too difficult of a fix :)

**Comment by cat-haines** [comment]
@analuisamartins - Fixed in the [v1.0.1 Branch](https://github.com/electricimp/Parse/blob/v1.0.1/).

Can you import that code and verify it fixes the issues you're seeing? Once it's verified we'll update our library system so you can `#require "parse.class.nut:1.0.1"`

**Comment by analuisamartins** [comment]
Hi @beardedinventor it's working, awesome! Thanks for this lib and your fast reply/fix :)

**Comment by cat-haines** [comment]
Fixed in [https://github.com/electricimp/Parse/pull/2](https://github.com/electricimp/Parse/pull/2) and pulled into Electric Imp's library system as `#require "parse.class.nut:1.0.1"`

Thanks for the find - and as a side note - I'd love to hear what you're building with Parse + Imp.. but outside the context of this ticket :)
